// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow that optimizes resume content.
 *
 * It takes resume text as input and uses an AI model to improve its impact and readability.
 *
 * @module ai/flows/optimize-resume-content
 *
 * @exports optimizeResumeContent - A function that optimizes the resume content.
 * @exports OptimizeResumeContentInput - The input type for the optimizeResumeContent function.
 * @exports OptimizeResumeContentOutput - The return type for the optimizeResumeContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for the optimizeResumeContent flow.
 */
const OptimizeResumeContentInputSchema = z.object({
  resumeSection: z.string().describe('The resume section to optimize.'),
  sectionType: z
    .string()
    .describe(
      'The type of resume section (e.g., Professional Summary, Experience, Education, Skills, etc.).'
    ),
});

/**
 * Type definition for the input of the optimizeResumeContent flow.
 */
export type OptimizeResumeContentInput = z.infer<typeof OptimizeResumeContentInputSchema>;

/**
 * Output schema for the optimizeResumeContent flow.
 */
const OptimizeResumeContentOutputSchema = z.object({
  optimizedContent: z
    .string()
    .describe('The optimized resume content with improved impact and readability.'),
});

/**
 * Type definition for the output of the optimizeResumeContent flow.
 */
export type OptimizeResumeContentOutput = z.infer<typeof OptimizeResumeContentOutputSchema>;

/**
 * Optimizes the given resume content using an AI model.
 *
 * @param {OptimizeResumeContentInput} input - The input for the optimization process.
 * @returns {Promise<OptimizeResumeContentOutput>} - The optimized resume content.
 */
export async function optimizeResumeContent(
  input: OptimizeResumeContentInput
): Promise<OptimizeResumeContentOutput> {
  return optimizeResumeContentFlow(input);
}

const optimizeResumeContentPrompt = ai.definePrompt({
  name: 'optimizeResumeContentPrompt',
  input: {
    schema: OptimizeResumeContentInputSchema,
  },
  output: {
    schema: OptimizeResumeContentOutputSchema,
  },
  prompt: `You are an AI resume optimization expert.

  You will receive a section of a resume, and its type (e.g., Professional Summary, Experience, Education, Skills, etc.).
  Your goal is to improve the impact and readability of the content by suggesting better wording and phrasing.

  Here is the resume section:
  {{resumeSection}}

  Here is the section type:
  {{sectionType}}

  Please provide the optimized content.
  `,
});

/**
 * Genkit flow for optimizing resume content.
 */
const optimizeResumeContentFlow = ai.defineFlow(
  {
    name: 'optimizeResumeContentFlow',
    inputSchema: OptimizeResumeContentInputSchema,
    outputSchema: OptimizeResumeContentOutputSchema,
  },
  async input => {
    const {output} = await optimizeResumeContentPrompt(input);
    return output!;
  }
);
